# Generated by Django 4.2.1 on 2023-05-09 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_myuser_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='balance',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]